TRANSITIVEBUILT=NO
GProtected=C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\ProtectedGenerated\win_b64
IProtected=C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\ProtectedInterfaces
MKMK_BSCMAKE=
IPublic=C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\PublicInterfaces
GPublic=C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\PublicGenerated\win_b64
GPrivate=C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\PrivateGenerated\win_b64
IPrivate=C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\PrivateInterfaces
F_DemoFW=mkFramework "C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW" DemoFW DemoFW - -
WSPATH=C:\Users\aidcadmin\Desktop\20210520\code\demo\.
FWNAME=DemoFW
WSROOT=C:\Users\aidcadmin\Desktop\20210520\code\demo\.
WSENAME_msg=DemoFW
NAME=C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\IdentityCard\Objects\win_b64\.mkdata.mkb
STEPS_TO_BUILD=fwcleanup headerlist headermap fwgrammar headerruler dummynls XrefDB cscinterface DoxGrammarFw cdg CIpackaging xmlctrl CIbuild imakecompil
WSEKEY=F_DemoFW
FW_AllPreq=BSFBuildtimeData,21DD1140;SpecialAPI,21ED1151;System,21EE1151;SystemTS,20CC1131;
FWCOMPANYNAME=
WS_Concat="C:\Users\aidcadmin\Desktop\20210520\code\demo\." "C:\Program Files\Dassault Systemes\B420\."
FWmkHLpath=C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\IdentityCard\Objects\win_b64\.mkHLpath.mk
RTViewDataListPath=C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\various\win_b64\framework.data
FWCOPYRIGHT=
FW_INCPATH="C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\PrivateInterfaces" "C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\PrivateGenerated\win_b64" "C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\ProtectedInterfaces" "C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\ProtectedGenerated\win_b64" "C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\PublicInterfaces" "C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\PublicGenerated\win_b64"
DOC_RTViewDataListPath=C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW\various\win_b64.doc\framework.data
FWPATH=C:\Users\aidcadmin\Desktop\20210520\code\demo\.\DemoFW
STEPS_TO_CLEAN=
FWDNAME=DemoFW
