//===================================================================
// COPYRIGHT AIDC 2021/05/21
//===================================================================
// DemoM.cpp
// Header definition of class DemoM
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/05/21 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByDemoM_H
#define ExportedByDemoM_H
#if defined(__DemoM)
# define ExportedByDemoM   DSYExport
#else // __DemoM
# define ExportedByDemoM   DSYImport
#endif  // __DemoM
#include "DSYExport.h"
#endif //ExportedByDemoM_H

